version: '3.9'

services:

  passportapi:
    image: ${DOCKER_REGISTRY-}passportapi
    build:
      context: .
      dockerfile: PassportRequestApi/Dockerfile
    container_name: passportapi
    depends_on: 
      - "mssqldb"
    ports:
      - '2004:2004'
    networks:
        - passport-network
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:2004
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mssqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqldb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "zyasevry"
      ACCEPT_EULA: "Y"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d