name: passportapi-runner

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Stop and remove containers
        working-directory: ./server
        run: docker-compose down
      - name: Remove unused data
        working-directory: ./server
        run: docker system prune -a -f
      - name: docker-compose
        working-directory: ./server
        run: docker-compose up -d