name: .NET

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./PassportRequestApi.sln
    - name: Build
      run: dotnet build PassportRequestApi/PassportRequestApi.csproj --configuration Release --no-restore
    - name: Test
      run:  dotnet test ./PassportRequestApi.sln --configuration Release --no-restore
